-- ==========================================================
-- AGENDA+ - AGENDA / APPOINTMENTS TABLE (FIXED v2)
-- ==========================================================

-- Redefine table to ensure all columns exist
DROP TABLE IF EXISTS public.appointments CASCADE;

CREATE TABLE public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  salon_id bigint REFERENCES public.salons(id) NOT NULL,
  professional_id bigint REFERENCES public.users(id) NOT NULL,
  client_name text NOT NULL,
  service_name text NOT NULL,
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  status text DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  created_at timestamptz DEFAULT now()
);

-- ENABLE RLS
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- 1. SELECT POLICIES
DROP POLICY IF EXISTS "Owners and Managers can view all salon appointments" ON public.appointments;
CREATE POLICY "Owners and Managers can view all salon appointments"
ON public.appointments FOR SELECT
USING (
  get_my_role() IN ('owner', 'manager') 
  AND salon_id = get_my_salon_id()
);

DROP POLICY IF EXISTS "Staff can view their own appointments" ON public.appointments;
CREATE POLICY "Staff can view their own appointments"
ON public.appointments FOR SELECT
USING (
  get_my_role() = 'staff'
  AND professional_id = (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email')
);

-- 2. INSERT/UPDATE/DELETE POLICIES
DROP POLICY IF EXISTS "Owners and Managers can manage all salon appointments" ON public.appointments;
CREATE POLICY "Owners and Managers can manage all salon appointments"
ON public.appointments FOR ALL
USING (
  get_my_role() IN ('owner', 'manager') 
  AND salon_id = get_my_salon_id()
)
WITH CHECK (
  get_my_role() IN ('owner', 'manager') 
  AND salon_id = get_my_salon_id()
);

DROP POLICY IF EXISTS "Staff can manage their own appointments" ON public.appointments;
CREATE POLICY "Staff can manage their own appointments"
ON public.appointments FOR ALL
USING (
  get_my_role() = 'staff'
  AND professional_id = (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email')
)
WITH CHECK (
  get_my_role() = 'staff'
  AND professional_id = (SELECT id FROM public.users WHERE email = auth.jwt() ->> 'email')
);
