-- ==========================================================
-- AGENDA+ - PAYMENTS SYSTEM
-- ==========================================================

-- 1. PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT REFERENCES public.salons(id) ON DELETE CASCADE,
    amount DECIMAL(10, 2) NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. ENABLE RLS
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- 3. RLS POLICIES

-- Only DEV can manage payments (INSERT, UPDATE, DELETE)
CREATE POLICY "Only devs can manage payments" 
ON public.payments FOR ALL 
USING (get_my_role() = 'DEV')
WITH CHECK (get_my_role() = 'DEV');

-- Owners can view payments of their own salon
CREATE POLICY "Owners can view their salon payments" 
ON public.payments FOR SELECT 
USING (
    get_my_role() = 'owner' 
    AND salon_id = get_my_salon_id()
);

-- DEV can view all payments
CREATE POLICY "Devs can view all payments" 
ON public.payments FOR SELECT 
USING (get_my_role() = 'DEV');
